### ISSUE TITLE
can't beautify the create table sql

### ISSUE THREAD

**Issue by wdt1988520** [vkiryukhin/vkBeautify#16]
eg:CREATE TABLE T_SHOP( SHOP_ID VARCHAR(32), CATE_ID VARCHAR(32), SHOP_NAME VARCHAR(128), START_DELI_MNY DOUBLE, DEPOSIT_BANK VARCHAR(128), CLEARING_ACCOUNT VARCHAR(128), SHOP_MANAGER VARCHAR(128), SHOP_ADDR VARCHAR(128), SHOP_EMAIL VARCHAR(128), SHOP_CONTACT VARCHAR(128), SHOP_CITIZEN_ID VARCHAR(128), SHOP_CERT TEXT, SHOP_LOGO_IMG TEXT, SHOP_HEAD_IMG TEXT, SHOP_DESC TEXT, GROSS_PROFIT DOUBLE, INVOICE_SUPT CHAR(1), ORDER_NUM INT, MODIFY_USER VARCHAR(32), CREATE_USER VARCHAR(32), MODIFY_DT DATETIME, IS_VALID CHAR(1), CREATE_DT DATETIME, DELI_MNY DOUBLE)

**Comment by vkiryukhin** [comment]
sql beautifier  is an experimental module within vkbeautify.js plugin. It was specifically  developed to beautify only simple SELECT statements for application I worked on that time. I don't plan to work on this module or improve it.
