### ISSUE TITLE
Licensing ambiguity

### ISSUE THREAD

**Issue by Bringer128** [vkiryukhin/vkBeautify#19]
According to [OpenSourceLaw](http://opensourcelaw.biz/publications/papers/BScott_OSS_Legal_Landscape_060328.pdf) a Dual Licensing arrangement can have requirements for accepting a particular license (e.g. requiring someone to pay to use a particular licensing model). Many dual licensed libraries explicitly state that either license may be chosen based on the preference of the person using it.

Could you add a license file to the project that states that either the GPL or MIT license may be chosen by the user of the library?

**Comment by yuxiaomin** [comment]
Yes. In my test vkBeautify has very good performance but I don't know if I can use it in my project due to license issue.
Can you update it?

**Comment by vkiryukhin** [comment]
I've updated license. It's MIT, you may use it without any restrictions.
