### ISSUE TITLE
ERROR TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by s-amasha** [vkiryukhin/vkBeautify#23]
Hi,
I was using this library with a project using SystemJS, now the project was moved to be using AngularCLI.
This issue appears only with the new CLI project.
The error is shown in the chrome console is :

> ERROR TypeError: Cannot read property '0' of undefined
>     at webpackJsonp.../../../../vkbeautify/index.js.vkbeautify.xml (index.js:134)

when I click on (index.js:134), I got the error in this line:
```
// <? xml ... ?> //
if(ar[ix].search(/<\?/) > -1) {
	str += shift[deep]+ar[ix];
} else
```

My setup is:
-Windows 7 x64
-Angular CLI : 1.0.1
-node : 6.10.2
-webpack : 2.5.1

I'm using this simple xml:
`<?xml version="1.0" encoding="UTF-8"?><note><to>Tove</to><from>Jani</from></note>`

Thanks

**Comment by vkiryukhin** [comment]
Hi s-amasha,
as this bug environment-dependent and I can't reproduce it on my computer, I have no idea how I can help you with this problem, sorry.
